theme: jekyll-theme-hacker

title: OfficePulse Growth Analytics Project
description: End-to-end growth analytics project using Python, DuckDB and dbt to load and transform raw data into analytical marts, define key growth metrics, and generate insights across acquisition, conversion, revenue, lead cohorts and product engagement.
url: "https://emmanuel-nti.github.io"
baseurl: "/OfficePulse_Growth_Analytics_Project"
